### ISSUE TITLE
installation error on Ubuntu - Could not find suitable distribution for Requirement.parse

### ISSUE THREAD

**Issue by haybeseret** [mediadrop/mediadrop#173]
t@MC:/var/www/mediacore# python setup.py develop
running develop
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running egg_info
writing paster_plugins to MediaCore.egg-info/paster_plugins.txt
writing requirements to MediaCore.egg-info/requires.txt
writing MediaCore.egg-info/PKG-INFO
writing top-level names to MediaCore.egg-info/top_level.txt
writing dependency_links to MediaCore.egg-info/dependency_links.txt
writing entry points to MediaCore.egg-info/entry_points.txt
reading manifest file 'MediaCore.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'doc/build'
warning: no previously-included files matching '_._' found under directory 'closure-library'
warning: no previously-included files matching '_._' found under directory 'batch-scripts/closure'
warning: no previously-included files matching '_.pyc' found under directory '_'
warning: no previously-included files matching '._.swp' found under directory '_'
warning: no previously-included files matching '.DS_Store' found under directory '*'
writing manifest file 'MediaCore.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python2.7/dist-packages/MediaCore.egg-link (link to .)
MediaCore 0.9.9dev is already the active version in easy-install.pth

Installed /var/www/mediacore
Processing dependencies for MediaCore==0.9.9dev
Searching for feedparser>=4.1
Reading http://mediacore.com/files/packages/

Link to http://pypi.python.org/simple/feedparser/ **_BLOCKED**_ by --allow-hosts

Couldn't find index page for 'feedparser' (maybe misspelled?)
Scanning index of all packages (this may take a while)

Link to http://pypi.python.org/simple/ **_BLOCKED**_ by --allow-hosts

No local packages or download links found for feedparser>=4.1
error: Could not find suitable distribution for Requirement.parse('feedparser>=4.1')

**Comment by njmulhsn** [comment]
@brainysmurf I am having the same issue. Even commenting out the allow host part in setup.cfg is not helping. The following is what I get:

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'paster_plugins'
  warnings.warn(msg)
Download error on http://static.mediadrop.video/dependencies/dev/: hostname 'static.mediadrop.video' doesn't match 'dev.mediadrop.video' -- Some packages may not be found!

Traceback (most recent call last):
  File "setup.py", line 106, in <module>
    **extra_arguments_for_setup
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 243, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 276, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/home/najam/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2060, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/home/najam/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 580, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/najam/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 818, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/home/najam/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 830, in obtain
    return installer(requirement)
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 314, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 581, in easy_install
    self.local_index
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/package_index.py", line 602, in fetch_distribution
    return dist.clone(location=self.download(dist.location, tmpdir))
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/package_index.py", line 518, in download
    found = self._download_url(scheme.group(1), spec, tmpdir)
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/package_index.py", line 766, in _download_url
    return self._attempt_download(url, filename)
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/package_index.py", line 772, in _attempt_download
    headers = self._download_to(url, filename)
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/package_index.py", line 682, in _download_to
    block = fp.read(bs)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 602, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
