### ISSUE TITLE
Beautifulsoup issue

### ISSUE THREAD

**Issue by hgillh** [mediadrop/mediadrop#178]
Hi, 
I am trying to configure mediadrop on my ubuntu server.
When I try to run : paster serve --reload deployment.ini , it give me following error.

Starting subprocess with file monitor
Traceback (most recent call last):
  File "/usr/local/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.3', 'console_scripts', 'paster')()
  File "/usr/local/lib/python2.7/dist-packages/PasteScript-1.7.3-py2.7.egg/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/PasteScript-1.7.3-py2.7.egg/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/PasteScript-1.7.3-py2.7.egg/paste/script/command.py", line 218, in run
    result = self.command()
  File "/usr/local/lib/python2.7/dist-packages/PasteScript-1.7.3-py2.7.egg/paste/script/serve.py", line 276, in command
    relative_to=base, global_conf=vars)
  File "/usr/local/lib/python2.7/dist-packages/PasteScript-1.7.3-py2.7.egg/paste/script/serve.py", line 313, in loadapp
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 204, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 224, in loadobj
    global_conf=global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 248, in loadcontext
    global_conf=global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 278, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 409, in get_context
    section)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 431, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 361, in get_context
    global_conf=global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 248, in loadcontext
    global_conf=global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 285, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 561, in get_context
    object_type, name=name)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.3.3-py2.7.egg/paste/deploy/loadwsgi.py", line 587, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/var/www/MediaCore/mediacore/config/middleware.py", line 34, in <module>
    from mediacore.config.environment import load_environment
  File "/var/www/MediaCore/mediacore/config/environment.py", line 19, in <module>
    import mediacore.lib.helpers
  File "/var/www/MediaCore/mediacore/lib/helpers.py", line 29, in <module>
    from mediacore.lib.auth import viewable_media
  File "/var/www/MediaCore/mediacore/lib/auth/__init__.py", line 3, in <module>
    from mediacore.lib.auth.middleware import *
  File "/var/www/MediaCore/mediacore/lib/auth/middleware.py", line 20, in <module>
    from mediacore.lib.auth.permission_system import MediaCorePermissionSystem
  File "/var/www/MediaCore/mediacore/lib/auth/permission_system.py", line 15, in <module>
    from mediacore.model import DBSession, Group, User
  File "/var/www/MediaCore/mediacore/model/__init__.py", line 21, in <module>
    from mediacore.lib.xhtml.htmlsanitizer import entities_to_unicode
  File "/var/www/MediaCore/mediacore/lib/xhtml/__init__.py", line 16, in <module>
    from mediacore.lib.xhtml.htmlsanitizer import (Cleaner,
  File "/var/www/MediaCore/mediacore/lib/xhtml/htmlsanitizer.py", line 42, in <module>
    tree=treebuilders.getTreeBuilder("beautifulsoup"),
  File "/usr/local/lib/python2.7/dist-packages/html5lib/treebuilders/__init__.py", line 75, in getTreeBuilder
    raise ValueError("""Unrecognised treebuilder "%s" """ % treeType)
ValueError: Unrecognised treebuilder "beautifulsoup"

BTW, I am using python 2.7 on ubuntu 12.04
Please let me to fix this issue.

Thanks
Harpreet Gill

**Comment by Soupala** [comment]
The pricklytech guide doesn't seem to solve it for me.  Has anyone figured out Bleach support already, or should I dig in?

**Comment by canatella** [comment]
I've got the same problem on ubuntu 14.04 too:

    ValueError: Unrecognised treebuilder "beautifulsoup"

Is there a workaround I can use, I'd like to evaluate mediadrop but as it is, I cannot do anything with it :(

**Comment by pokoli** [comment]
@FelixSchwarz  I have created a #205, but i don't know if i removed so much code. Just give a test on the admin and everyting seems to work well on my side. 

Can you give some feedback on the PR?

All the other could you test if the PR works well for you and report any issues found? 

Thanks.

**Comment by templar112** [comment]
Got the same issue here, I followed the same guide as @jojoob.

Trying to run in apache2 and I get the following in error log:

.......
[Mon Mar 30 12:19:33.854679 2015] [:error] [pid 2030] [remote 10.254.1.101:59245]     raise ValueError("""Unrecognised treebuilder "%s" """ % treeType)
[Mon Mar 30 12:19:33.854699 2015] [:error] [pid 2030] [remote 10.254.1.101:59245] ValueError: Unrecognised treebuilder "beautifulsoup"

**Comment by laocan** [comment]
I got the same problem, and tried many times.
Reason: set the wrong dir of "venv", so python cannot get the right path of beautifulsoup(suppose be ubder /venv/lib/python2.7/site-packages/)

**Comment by mvalin** [comment]
Hi Pokoli, I'm testing mediadrop on Ubuntu 14.04.2 and I found the same issue, I merge your fix "Replace BeautifulSoup with bleach to sanitanize html #205" with the original git/mediadrop and at least now I'm using mediadrop on Apache2 without problem until now, I think that your fix works. If I find something wrong I'll let you know.

Thank you for your help.

Regards
