### ISSUE TITLE
Version conflict of ToscaWidgets

### ISSUE THREAD

**Issue by natea** [mediadrop/mediadrop#189]
I tried to run the setup-app and got a version conflict with ToscaWidgets:

```
Traceback (most recent call last):
  File "/Users/nateaune/.virtualenvs/mediadrop/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/PasteScript-1.7.5-py2.7.egg/paste/script/command.py", line 93, in run
    commands = get_commands()
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/PasteScript-1.7.5-py2.7.egg/paste/script/command.py", line 135, in get_commands
    plugins = pluginlib.resolve_plugins(plugins)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/PasteScript-1.7.5-py2.7.egg/paste/script/pluginlib.py", line 82, in resolve_plugins
    pkg_resources.require(plugin)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/pkg_resources.py", line 742, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/pkg_resources.py", line 643, in resolve
    raise VersionConflict(dist, req) # XXX put more info here
pkg_resources.VersionConflict: (ToscaWidgets 0.9.12 (/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/ToscaWidgets-0.9.12-py2.7.egg), Requirement.parse('ToscaWidgets==0.9.9'))
```

So I installed ToscaWidgets==0.9.9, but then when I ran the command again, it complained that it needed v0.9.12 or above:

```
Traceback (most recent call last):
  File "/Users/nateaune/.virtualenvs/mediadrop/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.3', 'console_scripts', 'paster')()
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/script/appinstall.py", line 68, in run
    return super(AbstractInstallCommand, self).run(new_args)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/script/command.py", line 218, in run
    result = self.command()
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/script/appinstall.py", line 447, in command
    conf = appconfig(config_spec, relative_to=os.getcwd())
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 215, in appconfig
    global_conf=global_conf)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 248, in loadcontext
    global_conf=global_conf)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 278, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 409, in get_context
    section)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 431, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 361, in get_context
    global_conf=global_conf)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 248, in loadcontext
    global_conf=global_conf)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 285, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 561, in get_context
    object_type, name=name)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 581, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/pkg_resources.py", line 742, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages/pkg_resources.py", line 643, in resolve
    raise VersionConflict(dist, req) # XXX put more info here
pkg_resources.VersionConflict: (ToscaWidgets 0.9.9 (/Users/nateaune/.virtualenvs/mediadrop/lib/python2.7/site-packages), Requirement.parse('ToscaWidgets>=0.9.12'))
```

Which version of ToscaWidgets should I be using?

**Comment by github-users** [comment]
Hello MediaDrop Developers, 

Thank you for creating a great service. I have been able to use my Mediadrop application using the latest dev build (0.11dev) flawlessly (using Ubuntu 14.04 and Apache), and love the service. Now, I am needing to make a production build, and therefore using the latest stable build (0.10.3) the same way I was able to build the latest dev build. However, I am experiencing the same error that this thread started with while running this command: 
sudo paster setup-app deployment.ini

Error:

pkg_resources.VersionConflict: (ToscaWidgets 0.9.12 (/usr/local/lib/python2.7/dist-packages/ToscaWidgets-0.9.12-py2.7.egg), Requirement.parse('ToscaWidgets==0.9.9'))

I do not understand how this issue was resolved. I followed every step that was mentioned before, and still have the VersionConflict error with ToscaWidgets. Please advise. I am very familiar with MediaDrop and already have the dev build working flawlessly, which further aggravates me having this error with the stable build. 

Please help, thank you.
