### ISSUE TITLE
AttributeError: 'WSGIThreadPoolServer' object has no attribute 'thread_pool'

### ISSUE THREAD

**Issue by arthurlutz** [mediadrop/mediadrop#235]
While trying to run mediadrop I get the following traceback.

```
$ paster serve --reload development.ini 
Starting subprocess with file monitor
22:33:50,937 INFO  [alembic.migration] [MainThread] Context impl MySQLImpl.
22:33:50,937 INFO  [alembic.migration] [MainThread] Will assume transactional DDL.
Starting server in PID 3531.
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/mediacore/bin/paster", line 11, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/home/arthur/local/mediadrop/.eggs/PasteScript-1.7.5-py2.7.egg/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/home/arthur/local/mediadrop/.eggs/PasteScript-1.7.5-py2.7.egg/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/home/arthur/local/mediadrop/.eggs/PasteScript-1.7.5-py2.7.egg/paste/script/command.py", line 238, in run
    result = self.command()
  File "/home/arthur/local/mediadrop/.eggs/PasteScript-1.7.5-py2.7.egg/paste/script/serve.py", line 311, in command
    serve()
  File "/home/arthur/local/mediadrop/.eggs/PasteScript-1.7.5-py2.7.egg/paste/script/serve.py", line 295, in serve
    server(app)
  File "/home/arthur/local/mediadrop/.eggs/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/loadwsgi.py", line 189, in server_wrapper
    **context.local_conf)
  File "/home/arthur/local/mediadrop/.eggs/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/util.py", line 56, in fix_call
    val = callable(*args, **kw)
  File "/home/arthur/local/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1342, in server_runner
    serve(wsgi_app, **kwargs)
  File "/home/arthur/local/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1291, in serve
    request_queue_size=request_queue_size)
  File "/home/arthur/local/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1134, in __init__
    request_queue_size=request_queue_size)
  File "/home/arthur/local/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1113, in __init__
    request_queue_size=request_queue_size)
  File "/home/arthur/local/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 328, in __init__
    HTTPServer.__init__(self, server_address, RequestHandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_close()
  File "/home/arthur/local/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1105, in server_close
    self.thread_pool.shutdown(60)
AttributeError: 'WSGIThreadPoolServer' object has no attribute 'thread_pool'

```

**Comment by hominidae** [comment]
I've gotten the same error.

paster serve --reload production.ini
Starting subprocess with file monitor
22:30:57,686 INFO  [alembic.migration] [MainThread] Context impl MySQLImpl.
22:30:57,689 INFO  [alembic.migration] [MainThread] Will assume transactional DDL.
Starting server in PID 24350.
Traceback (most recent call last):
  File "/home/pi/src/mediadrop/mediadrop_env/bin/paster", line 11, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/home/pi/src/mediadrop/.eggs/PasteScript-1.7.5-py2.7.egg/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/home/pi/src/mediadrop/.eggs/PasteScript-1.7.5-py2.7.egg/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/home/pi/src/mediadrop/.eggs/PasteScript-1.7.5-py2.7.egg/paste/script/command.py", line 238, in run
    result = self.command()
  File "/home/pi/src/mediadrop/.eggs/PasteScript-1.7.5-py2.7.egg/paste/script/serve.py", line 311, in command
    serve()
  File "/home/pi/src/mediadrop/.eggs/PasteScript-1.7.5-py2.7.egg/paste/script/serve.py", line 295, in serve
    server(app)
  File "/home/pi/src/mediadrop/.eggs/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/loadwsgi.py", line 189, in server_wrapper
    **context.local_conf)
  File "/home/pi/src/mediadrop/.eggs/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/util.py", line 56, in fix_call
    val = callable(*args, **kw)
  File "/home/pi/src/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1342, in server_runner
    serve(wsgi_app, **kwargs)
  File "/home/pi/src/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1291, in serve
    request_queue_size=request_queue_size)
  File "/home/pi/src/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1134, in __init__
    request_queue_size=request_queue_size)
  File "/home/pi/src/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1113, in __init__
    request_queue_size=request_queue_size)
  File "/home/pi/src/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 328, in __init__
    HTTPServer.__init__(self, server_address, RequestHandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_close()
  File "/home/pi/src/mediadrop/.eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1105, in server_close
    self.thread_pool.shutdown(60)
AttributeError: 'WSGIThreadPoolServer' object has no attribute 'thread_pool'

**Comment by FelixSchwarz** [comment]
This happens if the dev server was unable to open the required port (e.g. insufficient privileges or port already in use by another MediaDrop instance/software). Check your "port = ..." setting in production.ini.

There is not much I can do about the problem but this will go away when we get rid of paste. If you are too annoyed about this you can use a different WSGI server, e.g. the one from werkzeug, waitress or gunicorn.
