### ISSUE TITLE
Installation error on debian jessie

### ISSUE THREAD

**Issue by goparklubanic** [mediadrop/mediadrop#238]
here is what happend where running script python setup.py develop

    (mediacore_env)xxxxxxx@myhost:~/mediadrop$ python setup.py develop
    Download error on http://static.mediadrop.video/dependencies/dev/: hostname 'static.mediadrop.video' doesn't match 'dev.mediadrop.video' -- Some packages may not be found!

    Note: Bypassing https://pypi.python.org/simple/PasteScript/ (disallowed host; see http://bit.ly/1dg9ijs for details).

    Couldn't find index page for 'PasteScript' (maybe misspelled?)

    Note: Bypassing https://pypi.python.org/simple/ (disallowed host; see http://bit.ly/1dg9ijs for details).

    No local packages or download links found for PasteScript>=1.7.4.2
    Traceback (most recent call last):
      File "setup.py", line 106, in <module>
        **extra_arguments_for_setup
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/xxxxxxx/mediacore_env/local/lib/python2.7/site-packages/setuptools/dist.py", line 262, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/xxxxxxx/mediacore_env/local/lib/python2.7/site-packages/setuptools/dist.py", line 287, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/xxxxxxx/mediacore_env/local/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/xxxxxxx/mediacore_env/local/lib/python2.7/site-packages/pkg_resources.py", line 874, in best_match
        return self.obtain(req, installer)
      File "/home/xxxxxxx/mediacore_env/local/lib/python2.7/site-packages/pkg_resources.py", line 886, in obtain
        return installer(requirement)
      File "/home/xxxxxxx/mediacore_env/local/lib/python2.7/site-packages/setuptools/dist.py", line 338, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/xxxxxxx/mediacore_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 630, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('PasteScript>=1.7.4.2')

**Comment by antonkovalenko** [comment]
Try installing PasteScript and all other dependencies via pip

`pip install PasteScript`

**Comment by FelixSchwarz** [comment]
Probably this is irrelevant by now but please try "pip install -r requirements.txt" before running "python setup.py". Also I pushed some updates and I verified installation works von Fedora 27 + Ubuntu 16.04.

Please reopen if you still experience problems on Debian Jessie.
