### ISSUE TITLE
Trouble installing latest version on Ubuntu 16.04

### ISSUE THREAD

**Issue by danikuci1** [mediadrop/mediadrop#245]
Hello,

I am having trouble running the mediadrop installation.

I am able to get to `python setup.py develop` ok but that step fails on me. After running for a few minutes, it spits out the following error:
```
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Exception in thread Thread-1 (most likely raised during interpreter shutdown):Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 366, in _handle_tasks

Traceback (most recent call last):<type 'exceptions.TypeError'>: 'NoneType' object is not callable
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 330, in _handle_workers
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <Finalize object, dead> ignored
```

I am unsure what to do to troubleshoot this, any assistance would be appreciated.

thanks.

**Comment by FelixSchwarz** [comment]
can you try to do this:

    # activate virtualenv before!
    pip install -r requirements.txt
    python setup.py develop?

Could be a problem in beautifulsoup.

**Comment by danikuci1** [comment]
thanks for the advice, this command went through and installed many many packages, however it exited with the error: ` Could not find a version that satisfies the requirement MySQL-python>=1.2.2 (from -r requirements.txt (line 29)) (from versions: )
No matching distribution found for MySQL-python>=1.2.2 (from -r requirements.txt (line 29))`

I'm not sure what package that is referring to. MySQL is definitely installed and running on the local server.

If I run the `python setup.py develop` command again, it exits with the same error info as above.

**Comment by FelixSchwarz** [comment]
Which version do you try to install? Best go with the git master as the dependencies for the other versions might be a bit old.

**Comment by danikuci1** [comment]
So i was using the hosted zip file and not GitHub. 

This morning I blew the VM away and reinstalled Ubuntu from media and updated, and attempted the install from scratch again. It errors in the same place. 

For an experiment I muted the line in `requirements.txt` that was causing the problem and re-ran `pip install -r requirements.txt` and it completed without any other issues. However, `python setup.py develop` still does not complete successfully.

Any other ideas? Should I try a different distro?

**Comment by FelixSchwarz** [comment]
Which version of MediaDrop are you trying to install? Please try the latest git master and paste/attach the output here (`pip install -r ...` before `setup.py develop`). Ubuntu 16.04 should be fine.

**Comment by danikuci1** [comment]
wasn't able to pick this back up for a few days. starting from freshly installed ubuntu, updating from default repos and installing prereqs ok. installed virtual environment and activated, and ran `pip install -r requirements.txt` everything installed ok up until the same `MySql-python` requirement.

```
Could not find a version that satisfies the requirement MySQL-python>=1.2.2 (from -r requirements.txt (line 29)) (from versions: )
No matching distribution found for MySQL-python>=1.2.2 (from -r requirements.txt (line 29))
```

Next I ran `python setup.py develop` regardless of that failed prereq. Here is the output:
```
Collecting iso8601 (from -r requirements.txt (line 2))â–ˆâ–ˆâ–ˆâ–ˆâ–
  Using cached https://static.mediadrop.video/dependencies/dev/iso8601/iso8601-0.1.10.tar.gz
Collecting ddt (from -r requirements.txt (line 3))ˆâ–ˆâ–ˆâ–ˆâ–
  Using cached https://static.mediadrop.video/dependencies/dev/ddt/ddt-0.4.0.tar.gz
Collecting formencode>=1.2.4 (from -r requirements.txt (line 4))
  Using cached https://static.mediadrop.video/dependencies/dev/formencode/FormEncode-1.2.6.zip
Collecting Pylons>=1.0 (from -r requirements.txt (line 5))
  Using cached https://static.mediadrop.video/dependencies/dev/pylons/Pylons-1.0.3-py2.py3-none-any.whl
Collecting WebOb>=1.1 (from -r requirements.txt (line 9))
  Using cached https://static.mediadrop.video/dependencies/dev/webob/WebOb-1.2.3.tar.gz
Collecting WebHelpers==1.0 (from -r requirements.txt (line 10))
  Using cached https://static.mediadrop.video/dependencies/dev/webhelpers/WebHelpers-1.0.tar.gz
Collecting SQLAlchemy<0.8,>=0.7.3 (from -r requirements.txt (line 13))
  Using cached https://static.mediadrop.video/dependencies/dev/sqlalchemy/SQLAlchemy-0.7.10.tar.gz
Collecting alembic>=0.4 (from -r requirements.txt (line 16))
  Using cached https://static.mediadrop.video/dependencies/dev/alembic/alembic-0.5.0.tar.gz
Collecting Genshi>=0.6 (from -r requirements.txt (line 17))
  Using cached https://static.mediadrop.video/dependencies/dev/genshi/Genshi-0.7.tar.gz
Collecting Babel>=1.0 (from -r requirements.txt (line 19))
  Using cached https://static.mediadrop.video/dependencies/dev/babel/Babel-1.3.tar.gz
Collecting Routes==1.12.3 (from -r requirements.txt (line 20))
  Using cached https://static.mediadrop.video/dependencies/dev/routes/Routes-1.12.3.tar.gz
Collecting repoze.who==1.0.18 (from -r requirements.txt (line 21))
  Using cached https://static.mediadrop.video/dependencies/dev/repoze-who/repoze.who-1.0.18.tar.gz
Collecting repoze.who-friendlyform (from -r requirements.txt (line 22))ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–
  Using cached https://static.mediadrop.video/dependencies/dev/repoze-who-friendlyform/repoze.who-friendlyform-1.0.8.tar.gz
Collecting repoze.who.plugins.sa (from -r requirements.txt (line 23))â–ˆâ–ˆâ–ˆâ–ˆâ–
  Using cached https://static.mediadrop.video/dependencies/dev/repoze-who-plugins-sa/repoze.who.plugins.sa-1.0.1.tar.gz
Collecting Paste>=1.7.5.1 (from -r requirements.txt (line 24))ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–
  Using cached https://static.mediadrop.video/dependencies/dev/paste/Paste-1.7.5.1.tar.gz
Collecting PasteScript>=1.7.4.2 (from -r requirements.txt (line 25))ˆâ–
  Using cached https://static.mediadrop.video/dependencies/dev/pastescript/PasteScript-1.7.5.tar.gz
Collecting PasteDeploy>=1.5 (from -r requirements.txt (line 26))
  Using cached https://static.mediadrop.video/dependencies/dev/pastedeploy/PasteDeploy-1.5.0.tar.gz
Collecting ToscaWidgets>=0.9.12 (from -r requirements.txt (line 27))
  Using cached https://static.mediadrop.video/dependencies/dev/toscawidgets/ToscaWidgets-0.9.12.tar.gz
Collecting tw.forms==0.9.9 (from -r requirements.txt (line 28))
  Using cached https://static.mediadrop.video/dependencies/dev/tw-forms/tw.forms-0.9.9.tar.gz
Collecting MySQL-python>=1.2.2 (from -r requirements.txt (line 29))
  Could not find a version that satisfies the requirement MySQL-python>=1.2.2 (from -r requirements.txt (line 29)) (from versions: )
No matching distribution found for MySQL-python>=1.2.2 (from -r requirements.txt (line 29))
(venv) root@jellyfish:/var/www/mediadrop-git# python setup.py develop
warning: no previously-included files matching '*' found under directory 'docs/_build/_sources'
warning: no files found matching '*.js' under directory 'paste'
warning: no files found matching '*.jpg' under directory 'paste'

Installed /var/www/mediadrop-git/.eggs/PasteScript-1.7.5-py2.7.egg
Searching for PasteDeploy
Reading https://static.mediadrop.video/dependencies/dev/
Downloading https://static.mediadrop.video/dependencies/dev/pastedeploy/PasteDeploy-1.5.0.tar.gz
Best match: PasteDeploy 1.5.0
Processing PasteDeploy-1.5.0.tar.gz
Writing /tmp/easy_install-dKKqTc/PasteDeploy-1.5.0/setup.cfg
Running PasteDeploy-1.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-dKKqTc/PasteDeploy-1.5.0/egg-dist-tmp-DPdM9M
creating /var/www/mediadrop-git/.eggs/PasteDeploy-1.5.0-py2.7.egg
Extracting PasteDeploy-1.5.0-py2.7.egg to /var/www/mediadrop-git/.eggs

Installed /var/www/mediadrop-git/.eggs/PasteDeploy-1.5.0-py2.7.egg
Searching for Paste>=1.3
Reading https://static.mediadrop.video/dependencies/dev/
Downloading https://static.mediadrop.video/dependencies/dev/paste/Paste-1.7.5.1.tar.gz
Best match: Paste 1.7.5.1
Processing Paste-1.7.5.1.tar.gz
Writing /tmp/easy_install-7aYiUm/Paste-1.7.5.1/setup.cfg
Running Paste-1.7.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7aYiUm/Paste-1.7.5.1/egg-dist-tmp-iYK8nU
warning: no previously-included files matching '*' found under directory 'docs/_build/_sources'
creating /var/www/mediadrop-git/.eggs/Paste-1.7.5.1-py2.7.egg
Extracting Paste-1.7.5.1-py2.7.egg to /var/www/mediadrop-git/.eggs

Installed /var/www/mediadrop-git/.eggs/Paste-1.7.5.1-py2.7.egg
/var/www/venv/local/lib/python2.7/site-packages/setuptools/dist.py:355: UserWarning: Normalizing '0.11dev' to '0.11.dev0'
  normalized_version,
running develop
running egg_info
creating MediaDrop.egg-info
writing paster_plugins to MediaDrop.egg-info/paster_plugins.txt
writing requirements to MediaDrop.egg-info/requires.txt
writing MediaDrop.egg-info/PKG-INFO
writing top-level names to MediaDrop.egg-info/top_level.txt
writing dependency_links to MediaDrop.egg-info/dependency_links.txt
writing entry points to MediaDrop.egg-info/entry_points.txt
writing manifest file 'MediaDrop.egg-info/SOURCES.txt'
reading manifest file 'MediaDrop.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'ez_setup.py'
warning: no previously-included files matching '*.*' found under directory 'data/images/media'
warning: no previously-included files matching '*.*' found under directory 'data/images/podcasts'
no previously-included directories found matching 'doc/build'
warning: no previously-included files matching '*.*' found under directory 'closure-library'
warning: no previously-included files matching '*.*' found under directory 'batch-scripts/closure'
warning: no previously-included files matching '*.pyc' found under directory '*'
warning: no previously-included files matching '.*.swp' found under directory '*'
warning: no previously-included files matching '.DS_Store' found under directory '*'
writing manifest file 'MediaDrop.egg-info/SOURCES.txt'
running build_ext
Creating /var/www/venv/lib/python2.7/site-packages/MediaDrop.egg-link (link to .)
Adding MediaDrop 0.11.dev0 to easy-install.pth file

Installed /var/www/mediadrop-git
Processing dependencies for MediaDrop==0.11.dev0
Searching for bleach>=1.4.1
Reading https://static.mediadrop.video/dependencies/dev/
Downloading https://static.mediadrop.video/dependencies/dev/bleach/bleach-1.4.2-py2.py3-none-any.whl
Best match: bleach 1.4.2
Processing bleach-1.4.2-py2.py3-none-any.whl
Installing bleach-1.4.2-py2.py3-none-any.whl to /var/www/venv/lib/python2.7/site-packages
writing requirements to /var/www/venv/lib/python2.7/site-packages/bleach-1.4.2-py2.7.egg/EGG-INFO/requires.txt
Adding bleach 1.4.2 to easy-install.pth file

Installed /var/www/venv/lib/python2.7/site-packages/bleach-1.4.2-py2.7.egg
Searching for aniso8601==1.0.0
Downloading https://static.mediadrop.video/dependencies/dev/aniso8601/aniso8601-1.0.0.tar.gz
Best match: aniso8601 1.0.0
Processing aniso8601-1.0.0.tar.gz
Writing /tmp/easy_install-BmdeqV/aniso8601-1.0.0/setup.cfg
Running aniso8601-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BmdeqV/aniso8601-1.0.0/egg-dist-tmp-i6cSWM
zip_safe flag not set; analyzing archive contents...
Moving aniso8601-1.0.0-py2.7.egg to /var/www/venv/lib/python2.7/site-packages
Adding aniso8601 1.0.0 to easy-install.pth file

Installed /var/www/venv/lib/python2.7/site-packages/aniso8601-1.0.0-py2.7.egg
Searching for simplejson>=2.2.1
Downloading https://static.mediadrop.video/dependencies/dev/simplejson/simplejson-3.2.0.tar.gz
Best match: simplejson 3.2.0
Processing simplejson-3.2.0.tar.gz
Writing /tmp/easy_install-4dLTor/simplejson-3.2.0/setup.cfg
Running simplejson-3.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-4dLTor/simplejson-3.2.0/egg-dist-tmp-agBieK
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
***************************************************************************
WARNING: The C extension could not be compiled, speedups are not enabled.
Failure information, if any, is above.
I'm retrying the build without the C extension now.
***************************************************************************
zip_safe flag not set; analyzing archive contents...
simplejson.tests.__init__: module references __file__
***************************************************************************
WARNING: The C extension could not be compiled, speedups are not enabled.
Plain-Python installation succeeded.
***************************************************************************
creating /var/www/venv/lib/python2.7/site-packages/simplejson-3.2.0-py2.7.egg
Extracting simplejson-3.2.0-py2.7.egg to /var/www/venv/lib/python2.7/site-packages
Adding simplejson 3.2.0 to easy-install.pth file

Installed /var/www/venv/lib/python2.7/site-packages/simplejson-3.2.0-py2.7.egg
Searching for decorator>=3.3.2
Downloading https://static.mediadrop.video/dependencies/dev/decorator/decorator-3.4.0.tar.gz
Best match: decorator 3.4.0
Processing decorator-3.4.0.tar.gz
Writing /tmp/easy_install-9iYWki/decorator-3.4.0/setup.cfg
Running decorator-3.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9iYWki/decorator-3.4.0/egg-dist-tmp-121sdn
warning: no previously-included files found matching 'Makefile'
creating /var/www/venv/lib/python2.7/site-packages/decorator-3.4.0-py2.7.egg
Extracting decorator-3.4.0-py2.7.egg to /var/www/venv/lib/python2.7/site-packages
Adding decorator 3.4.0 to easy-install.pth file

Installed /var/www/venv/lib/python2.7/site-packages/decorator-3.4.0-py2.7.egg
Searching for unidecode
Downloading https://static.mediadrop.video/dependencies/dev/unidecode/Unidecode-0.04.5.tar.gz
Best match: Unidecode 0.4.5
Processing Unidecode-0.04.5.tar.gz
Writing /tmp/easy_install-ymYuD0/Unidecode-0.04.5/setup.cfg
Running Unidecode-0.04.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ymYuD0/Unidecode-0.04.5/egg-dist-tmp-5unpvk
/var/www/venv/local/lib/python2.7/site-packages/setuptools/dist.py:355: UserWarning: Normalizing '0.04.5' to '0.4.5'
  normalized_version,
zip_safe flag not set; analyzing archive contents...
Moving Unidecode-0.4.5-py2.7.egg to /var/www/venv/lib/python2.7/site-packages
Adding Unidecode 0.4.5 to easy-install.pth file

Installed /var/www/venv/lib/python2.7/site-packages/Unidecode-0.4.5-py2.7.egg
Searching for google-api-python-client
Downloading https://static.mediadrop.video/dependencies/dev/google-api-python-client/google-api-python-client-1.4.1.tar.gz
Best match: google-api-python-client 1.4.1
Processing google-api-python-client-1.4.1.tar.gz
Writing /tmp/easy_install-FRsuUY/google-api-python-client-1.4.1/setup.cfg
Running google-api-python-client-1.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-FRsuUY/google-api-python-client-1.4.1/egg-dist-tmp-YT6azl
warning: no files found matching '*.json' under directory 'apiclient'
warning: no files found matching 'README'
warning: no files found matching 'FAQ'
warning: no files found matching 'setpath.sh'
zip_safe flag not set; analyzing archive contents...
Moving google_api_python_client-1.4.1-py2.7.egg to /var/www/venv/lib/python2.7/site-packages
Adding google-api-python-client 1.4.1 to easy-install.pth file

Installed /var/www/venv/lib/python2.7/site-packages/google_api_python_client-1.4.1-py2.7.egg
Searching for akismet==0.2.0
Downloading https://static.mediadrop.video/dependencies/dev/akismet/akismet-0.2.0.tar.gz
Best match: akismet 0.2.0
Processing akismet-0.2.0.tar.gz
Writing /tmp/easy_install-jmCXIY/akismet-0.2.0/setup.cfg
Running akismet-0.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jmCXIY/akismet-0.2.0/egg-dist-tmp-5QXR4O
zip_safe flag not set; analyzing archive contents...
Moving akismet-0.2.0-py2.7.egg to /var/www/venv/lib/python2.7/site-packages
Adding akismet 0.2.0 to easy-install.pth file

Installed /var/www/venv/lib/python2.7/site-packages/akismet-0.2.0-py2.7.egg
Searching for Pillow
Downloading https://static.mediadrop.video/dependencies/dev/pillow/Pillow-3.4.2.tar.gz
Best match: Pillow 3.4.2
Processing Pillow-3.4.2.tar.gz
Writing /tmp/easy_install-6Ix0oh/Pillow-3.4.2/setup.cfg
Running Pillow-3.4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6Ix0oh/Pillow-3.4.2/egg-dist-tmp-vmPIQ0
warning: no files found matching '*.sh'
no previously-included directories found matching 'docs/_static'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.landscape.yaml'
warning: no previously-included files found matching 'appveyor.yml'
warning: no previously-included files found matching 'build_children.sh'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Building using 2 processes
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Exception in thread Thread-1 (most likely raised during interpreter shutdown):Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 366, in _handle_tasks
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 330, in _handle_workers
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <Finalize object, dead> ignored
```

This is with the latest version available from github, obtained using ` git clone git://github.com/mediadrop/mediadrop.git mediadrop-git`

**Comment by FelixSchwarz** [comment]
I just pushed a few changes to "requirements.txt". With the updated dependency versions you should be able to install MediaDrop on modern distros (e.g. Fedora 27). I tried again on a fresh Ubuntu 16.04 and it worked there as well.

Feel free to reopen in case you still experience problems.
