### ISSUE TITLE
Setup: paster make-config MediaDrop deployment.ini fails

### ISSUE THREAD

**Issue by TMorville** [mediadrop/mediadrop#248]
I am in a conda env, Python 2.7 with PasteScript 2.0.2 and I get the follow error message:

```
Traceback (most recent call last):
  File "/anaconda3/envs/drop/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/anaconda3/envs/drop/lib/python2.7/site-packages/paste/script/command.py", line 91, in run
    commands = get_commands()
  File "/anaconda3/envs/drop/lib/python2.7/site-packages/paste/script/command.py", line 133, in get_commands
    plugins = pluginlib.resolve_plugins(plugins)
  File "/anaconda3/envs/drop/lib/python2.7/site-packages/paste/script/pluginlib.py", line 83, in resolve_plugins
    pkg_resources.require(plugin)
  File "/anaconda3/envs/drop/lib/python2.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/anaconda3/envs/drop/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: <exception str() failed>
```
Is there an alternative to Paster when creating deployment.ini?

**Comment by dhirendra31pandit** [comment]
I had the same issue and I fixed by uninstalling the new version of python. Please keep only python 2.6 or 2.7 version for run.
